name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Start services
      run: docker-compose up -d
  
    - name: Run eslint
      run: |
        docker exec -t=false ecomm-account npm run lint
  
    - name: Run jest/supertest checks
      run: |
        docker exec -t=false ecomm-account npm test
  
    - name: Stop services
      run: docker-compose down
