name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start services
      run: docker-compose up -d

    - name: Print logs for all containers
      run: docker-compose logs
  
    - name: Run eslint
      run: |
        docker-compose exec account npm run lint --debug;
        docker-compose exec api-gateway npm run lint --debug;
        docker-compose exec finance npm run lint --debug;
        docker-compose exec order npm run lint --debug;
        docker-compose exec product npm run lint --debug;
  
    - name: Run jest/supertest checks
      run: |
        docker-compose exec account npm test;
        docker-compose exec finance npm test;
        docker-compose exec order npm test;
        docker-compose exec product npm test;
  
    - name: Stop services
      run: docker-compose down
