name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: docker exec order npm install
  
    - name: Run eslint
      shell: 'script -q -e -c "bash {0}"'
      run: |
        docker exec -t=false order npm run lint --max-workers=1
  
    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: |
        docker exec ecomm-order npm test
  
    - name: Stop services
      run: docker-compose down
