name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        volumes:
          - db-mongo-ecomm:/data/db
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
      order:
        build: ./order
        volumes:
          - ./order/:/app/ecomm-order
        ports:
          - 3004:3004
        depends_on:
          - mongodb

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: docker exec order npm install
  
    - name: Run eslint
      shell: 'script -q -e -c "bash {0}"'
      run: |
        docker exec -t=false order npm run lint --max-workers=1
  
    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: |
        docker exec ecomm-order npm test
  
    - name: Stop services
      run: docker-compose down

volumes:
  db-mongo-ecomm: