name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start services
      run: docker-compose up -d

    - name: Print logs for all containers
      run: docker-compose logs
  
    - name: Install dependencies
    run: |
      cd account && npm install
      cd ../api-gateway && npm install
      cd ../finance && npm install
      cd ../order && npm install
      cd ../product && npm install
  
    - name: Run eslint checks
      run: |
        cd account && npm run lint
        cd ../api-gateway && npm run lint
        cd ../finance && npm run lint
        cd ../order && npm run lint
        cd ../product && npm run lint
  
    - name: Run jest/supertest checks
      run: |
        docker-compose exec account npm test;
        docker-compose exec finance npm test;
        docker-compose exec order npm test;
        docker-compose exec product npm test;
  
    - name: Stop services
      run: docker-compose down
